#!/usr/bin/env python3

"""Sync shared Mermaid diagrams into markdown files.

GitHub-flavored Markdown does not support native includes/templating.
This script keeps a single Mermaid source file and injects it into
multiple markdown files between HTML comment markers.

Markers:
  <!-- DIAGRAM:<name> -->
  <!-- /DIAGRAM:<name> -->
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class Diagram:
    name: str
    mermaid_path: Path

    def render_markdown(self) -> str:
        src = self.mermaid_path.read_text(encoding="utf-8").rstrip() + "\n"
        return "```mermaid\n" + src + "```\n"

    def render_note(self) -> str:
        rel = self.mermaid_path.relative_to(REPO_ROOT)
        return f"<!-- (auto-generated by scripts/sync-diagrams.py; edit {rel}) -->"


DIAGRAMS: dict[str, Diagram] = {
    "system": Diagram(
        name="system",
        mermaid_path=REPO_ROOT / "docs" / "diagrams" / "system.mermaid",
    )
}

TARGETS: list[Path] = [
    REPO_ROOT / "README.md",
    REPO_ROOT / "docs" / "architecture.md",
]


def sync_file(path: Path, diagrams: dict[str, Diagram]) -> bool:
    original = path.read_text(encoding="utf-8")
    text = original
    changed = False

    for name, diagram in diagrams.items():
        start = f"<!-- DIAGRAM:{name} -->"
        end = f"<!-- /DIAGRAM:{name} -->"

        start_i = text.find(start)
        end_i = text.find(end)
        if start_i == -1 and end_i == -1:
            continue
        if start_i == -1 or end_i == -1 or end_i < start_i:
            raise SystemExit(f"Malformed markers for diagram '{name}' in {path}")

        before = text[: start_i + len(start)]
        after = text[end_i:]

        injected = "\n" + diagram.render_note() + "\n" + diagram.render_markdown() + after
        new_text = before + injected

        if new_text != text:
            changed = True
            text = new_text

    if changed:
        path.write_text(text, encoding="utf-8")
    return changed


def main() -> int:
    # Ensure all declared targets exist (pre-commit can run from subdirs).
    for target in TARGETS:
        if not target.exists():
            sys.stderr.write(f"sync-diagrams: missing target {target}\n")
            return 2

    any_changed = False
    for target in TARGETS:
        any_changed |= sync_file(target, DIAGRAMS)
    if any_changed:
        sys.stderr.write(
            "sync-diagrams: updated markdown from docs/diagrams/*.mermaid; re-stage files and retry\n"
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
